name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          # Don't test Node.js 8 on Windows. npm is weird here
          - os: windows-latest
            node-version: 8.x

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Install Test
      run: npm install
      
    - name: Run UnitTests
      run: npm test
      env:
        CI: true
